/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dictionary;

import java.awt.event.KeyEvent;

/**
 *
 * @author tuan
 */
public class MainWindown extends javax.swing.JFrame {

    /**
     * Creates new form MainWindown
     */
    public MainWindown() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        fastReferButton = new javax.swing.JButton();
        myWordsButton = new javax.swing.JButton();
        wordsReferedButton = new javax.swing.JButton();
        knowledgeAdditionalButton = new javax.swing.JButton();
        aboutUsButton = new javax.swing.JButton();
        settingButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1024, 960));

        jPanel1.setBackground(new java.awt.Color(111, 177, 213));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(53, 222, 41));
        jLabel1.setText("DHD");

        jTextField1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jTextField1.setToolTipText("Tra tên nguyên liệu hóa dược và thành phần hóa dược");
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(245, 245, 245))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 26, Short.MAX_VALUE))
        );

        fastReferButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        fastReferButton.setText("Cửa sổ tra nhanh");
        fastReferButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fastReferButtonMouseClicked(evt);
            }
        });

        myWordsButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        myWordsButton.setText("Từ của bạn");
        myWordsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                myWordsButtonMouseClicked(evt);
            }
        });

        wordsReferedButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        wordsReferedButton.setText("Từ đã tra");
        wordsReferedButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wordsReferedButtonMouseClicked(evt);
            }
        });

        knowledgeAdditionalButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        knowledgeAdditionalButton.setText("Kiến thức phụ trợ");

        aboutUsButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        aboutUsButton.setText("Về chúng tôi");
        aboutUsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutUsButtonMouseClicked(evt);
            }
        });

        settingButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        settingButton.setText("Cài đặt");
        settingButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(115, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aboutUsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(myWordsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(wordsReferedButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(knowledgeAdditionalButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fastReferButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                        .addComponent(settingButton, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)))
                .addGap(114, 114, 114))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fastReferButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(myWordsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(wordsReferedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(knowledgeAdditionalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(settingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(aboutUsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void settingButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingButtonMouseClicked
        // TODO add your handling code here:
        SettingWindown sw = new SettingWindown();
        this.hide();
        sw.setVisible(true);
    }//GEN-LAST:event_settingButtonMouseClicked

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            ReferWindown rw = new ReferWindown();
            this.hide();
            rw.setVisible(true);
            rw.jTextField1.setText(jTextField1.getText());
            rw.jLabel6.setText(jTextField1.getText());
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void aboutUsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutUsButtonMouseClicked
        // TODO add your handling code here:
        QuestionWindown qw = new QuestionWindown();
        qw.jLabel1.setText("Về chúng tôi");
        String s = "Đây là sản phẩm phục vụ cho môn lập trình nâng cao\n"
                + "Sản phẩm này nhằm mục đích phục vụ học tập, không mang tính thương mại\n"
                + "Đề nghị không sử dụng cho mục đích thương mại\n"
                + "Các kiến thức trong sản phẩm được lấy từ trong tài liệu của Dược điển Việt Nam\n";
        qw.jTextArea1.setText(s);
        this.hide();
        qw.setVisible(true);
    }//GEN-LAST:event_aboutUsButtonMouseClicked

    private void fastReferButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fastReferButtonMouseClicked
        // TODO add your handling code here:
        FastReferWindown frw = new FastReferWindown();
        this.hide();
        frw.setVisible(true);
    }//GEN-LAST:event_fastReferButtonMouseClicked

    private void myWordsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myWordsButtonMouseClicked
        // TODO add your handling code here:
        QuestionWindown qw = new QuestionWindown();
        qw.jLabel1.setText("Từ của bạn");
        this.hide();
        qw.setVisible(true);
    }//GEN-LAST:event_myWordsButtonMouseClicked

    private void wordsReferedButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wordsReferedButtonMouseClicked
        // TODO add your handling code here:
        QuestionWindown qw = new QuestionWindown();
        qw.jLabel1.setText("Từ đã tra");
        this.hide();
        qw.setVisible(true);
    }//GEN-LAST:event_wordsReferedButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindown.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindown.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindown.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindown.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindown().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aboutUsButton;
    private javax.swing.JButton fastReferButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton knowledgeAdditionalButton;
    private javax.swing.JButton myWordsButton;
    private javax.swing.JButton settingButton;
    private javax.swing.JButton wordsReferedButton;
    // End of variables declaration//GEN-END:variables
}
